<a href="https://colab.research.google.com/github/byambaa1982/python_cources_for_beginers/blob/main/titanic_data_analysis/basic_sql_practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import sqlite3


# SQL

- Step 1. Download titanic.sqlite

- step 2. Upload file into notebook

- step 3. Run the first two cells

In [ ]:
# Connect to the SQLite database
conn = sqlite3.connect('titanic.sqlite')

# Read the 'titanic' table into a pandas DataFrame
df = pd.read_sql('SELECT * FROM titanic', conn)
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,None,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,None,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,None,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,None,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,None,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,None,Q

# Use 'PassengerId', 'Name', 'Sex', 'Age' columns and save dataframe into database as passenger_info

In [ ]:
# 1. Passenger Info Table
passenger_info = df[['PassengerId', 'Name', 'Sex', 'Age']]
passenger_info.to_sql('passenger_info', conn, if_exists='replace', index=False)

# 2. Ticket Info Table
ticket_info = df[['PassengerId', 'Ticket', 'Fare', 'Pclass']]
ticket_info.to_sql('ticket_info', conn, if_exists='replace', index=False)

# 3. Survival Status Table
survival_status = df[['PassengerId', 'Survived', 'Parch', 'SibSp']]
survival_status.to_sql('survival_status', conn, if_exists='replace', index=False)

In [ ]:
tables = pd.read_sql("SELECT name FROM sqlite_master WHERE type='table'", conn)
print(tables)

              name
0          titanic
1   passenger_info
2      ticket_info
3  survival_status

In [ ]:
q = '''
select PassengerId, Name from passenger_info limit 5
'''
p_info = pd.read_sql(q, conn)
p_info

   PassengerId                                               Name
0            1                            Braund, Mr. Owen Harris
1            2  Cumings, Mrs. John Bradley (Florence Briggs Th...
2            3                             Heikkinen, Miss. Laina
3            4       Futrelle, Mrs. Jacques Heath (Lily May Peel)
4            5                           Allen, Mr. William Henry

In [ ]:
q = """
SELECT
    passenger_info.PassengerId,
    passenger_info.Name,
    ticket_info.Ticket
FROM
    passenger_info
JOIN
    ticket_info
ON
    passenger_info.PassengerId = ticket_info.PassengerId;
"""

df = pd.read_sql_query(q, conn)

df

,PassengerId,Name,Ticket
0,1,"Braund, Mr. Owen Harris",A/5 21171
1,2,"Cumings, Mrs. John Bradley (Florence Briggs Th...",PC 17599
2,3,"Heikkinen, Miss. Laina",STON/O2. 3101282
3,4,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",113803
4,5,"Allen, Mr. William Henry",373450
...,...,...,...
886,887,"Montvila, Rev. Juozas",211536
887,888,"Graham, Miss. Margaret Edith",112053
888,889,"Johnston, Miss. Catherine Helen ""Carrie""",W./C. 6607
889,890,"Behr, Mr. Karl Howell",111369
890,891,"Dooley, Mr. Patrick",370376

In [ ]:
my_query = '''

SELECT
    passenger_info.PassengerId,
    Name,
    Sex,
    Age,
    Ticket,
    Fare,
    Pclass,
    Survived,
    Parch,
    SibSp
FROM
    passenger_info
JOIN
    ticket_info
ON
    passenger_info.PassengerId = ticket_info.PassengerId
JOIN
    survival_status
ON
    passenger_info.PassengerId = survival_status.PassengerId;

'''

In [ ]:
df = pd.read_sql(my_query, conn)

df

,PassengerId,Name,Sex,Age,Ticket,Fare,Pclass,Survived,Parch,SibSp
0,1,"Braund, Mr. Owen Harris",male,22.0,A/5 21171,7.2500,3,0,0,1
1,2,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,PC 17599,71.2833,1,1,0,1
2,3,"Heikkinen, Miss. Laina",female,26.0,STON/O2. 3101282,7.9250,3,1,0,0
3,4,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,113803,53.1000,1,1,0,1
4,5,"Allen, Mr. William Henry",male,35.0,373450,8.0500,3,0,0,0
...,...,...,...,...,...,...,...,...,...,...
886,887,"Montvila, Rev. Juozas",male,27.0,211536,13.0000,2,0,0,0
887,888,"Graham, Miss. Margaret Edith",female,19.0,112053,30.0000,1,1,0,0
888,889,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,W./C. 6607,23.4500,3,0,2,1
889,890,"Behr, Mr. Karl Howell",male,26.0,111369,30.0000,1,1,0,0
890,891,"Dooley, Mr. Patrick",male,32.0,370376,7.7500,3,0,0,0

In [ ]:
# PassengerId, Name, Survived for Survived is I

#burnee_survived

In [ ]:
# PassengerId, Name, Secv for Female

In [ ]:
# PassengerId, Name, Ticket for male

# Task1
- Write a SQL query to join the passenger_info and ticket_info tables on PassengerId and select the following columns:

- PassengerId
- Name
- Ticket
- Fare
## Question: Find all passengers who paid more than $50 for their ticket.

##  Question: List the names of all passengers who survived and were in Pclass

1. Select
2. Join