<a href="https://colab.research.google.com/github/byambaa1982/python_cources_for_beginers/blob/class_zero_burentugs/titanic_data_analysis/basic_sql.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import sqlite3

In [9]:
# Connect to the SQLite database
conn = sqlite3.connect('titanic.sqlite')

# Read the 'titanic' table into a pandas DataFrame
df = pd.read_sql('SELECT * FROM titanic limit 3', conn)

df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,None,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,None,S

In [10]:

query = '''
SELECT
FROM
WHERE
ORDER BY
LIMIT
'''

In [11]:
query = '''
select Name, Sex, Age from titanic where Sex = "male" order by Age desc limit 10
'''

df = pd.read_sql(query, conn)

df

                                   Name   Sex   Age
0  Barkworth, Mr. Algernon Henry Wilson  male  80.0
1                   Svensson, Mr. Johan  male  74.0
2             Goldschmidt, Mr. George B  male  71.0
3               Artagaveytia, Mr. Ramon  male  71.0
4                  Connors, Mr. Patrick  male  70.5
5           Mitchell, Mr. Henry Michael  male  70.0
6          Crosby, Capt. Edward Gifford  male  70.0
7                 Wheadon, Mr. Edward H  male  66.0
8        Ostby, Mr. Engelhart Cornelius  male  65.0
9                      Duane, Mr. Frank  male  65.0

In [5]:
df2 = df[["Name", "Sex", "Age"]]
df2[df2['Sex']=='male'].sort_values('Age')

                                   Name   Sex   Age
8        Ostby, Mr. Engelhart Cornelius  male  65.0
9                      Duane, Mr. Frank  male  65.0
7                 Wheadon, Mr. Edward H  male  66.0
5           Mitchell, Mr. Henry Michael  male  70.0
6          Crosby, Capt. Edward Gifford  male  70.0
4                  Connors, Mr. Patrick  male  70.5
2             Goldschmidt, Mr. George B  male  71.0
3               Artagaveytia, Mr. Ramon  male  71.0
1                   Svensson, Mr. Johan  male  74.0
0  Barkworth, Mr. Algernon Henry Wilson  male  80.0


# Task 1: Select Specific Columns

- Write an SQL query to display only the Name, Age, and Survived columns from the Titanic dataset.

# Task 2: Filtering Rows

- Write an SQL query to display passengers who were under 18 years old.

# Task 3: Count Passengers by Survival Status

- Write an SQL query to count how many passengers survived and how many did not.

In [34]:
query = '''
select Name, Age, Survived from titanic where Survived
'''
df = pd.read_sql(query, conn)

df

                                                  Name   Age  Survived
0    Cumings, Mrs. John Bradley (Florence Briggs Th...  38.0         1
1                               Heikkinen, Miss. Laina  26.0         1
2         Futrelle, Mrs. Jacques Heath (Lily May Peel)  35.0         1
3    Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  27.0         1
4                  Nasser, Mrs. Nicholas (Adele Achem)  14.0         1
..                                                 ...   ...       ...
337                   Najib, Miss. Adele Kiamie "Jane"  15.0         1
338      Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)  56.0         1
339       Shelley, Mrs. William (Imanita Parrish Hall)  25.0         1
340                       Graham, Miss. Margaret Edith  19.0         1
341                              Behr, Mr. Karl Howell  26.0         1

[342 rows x 3 columns]

In [14]:
query = '''
select Name, Age, Survived from titanic where Age <18
'''
df = pd.read_sql(query, conn)

df

                                        Name   Age  Survived
0             Palsson, Master. Gosta Leonard   2.0         0
1        Nasser, Mrs. Nicholas (Adele Achem)  14.0         1
2            Sandstrom, Miss. Marguerite Rut   4.0         1
3       Vestrom, Miss. Hulda Amanda Adolfina  14.0         0
4                       Rice, Master. Eugene   2.0         0
..                                       ...   ...       ...
108  Andersson, Master. Sigvard Harald Elias   4.0         0
109                  Boulos, Miss. Nourelain   9.0         0
110                Lines, Miss. Mary Conover  16.0         1
111          Johnson, Master. Harold Theodor   4.0         1
112         Najib, Miss. Adele Kiamie "Jane"  15.0         1

[113 rows x 3 columns]

In [41]:
query = '''
select count(*) passengers from titanic where Survived
'''
df = pd.read_sql(query, conn)

df

   passengers
0         342

# Task 4: Sorting the Data

- Write an SQL query to display the names and ages of passengers, sorted by age in descending order (from oldest to youngest).

# Task 5: Finding the Average Age

- Write an SQL query to calculate the average age of all passengers.

# Task 6: Counting Passengers by Embarked Port

- Write an SQL query to count how many passengers embarked from each port (Embarked column).

In [43]:
query = '''
select Name, Age from titanic order by Age desc
'''
df = pd.read_sql(query, conn)

df

                                         Name   Age
0        Barkworth, Mr. Algernon Henry Wilson  80.0
1                         Svensson, Mr. Johan  74.0
2                   Goldschmidt, Mr. George B  71.0
3                     Artagaveytia, Mr. Ramon  71.0
4                        Connors, Mr. Patrick  70.5
..                                        ...   ...
886                          Razi, Mr. Raihed   NaN
887         Sage, Miss. Dorothy Edith "Dolly"   NaN
888               van Melkebeke, Mr. Philemon   NaN
889                        Laleff, Mr. Kristo   NaN
890  Johnston, Miss. Catherine Helen "Carrie"   NaN

[891 rows x 2 columns]

In [48]:
query = '''
select Name, Age, Survived from titanic df['Age'].mean()
'''
df = pd.read_sql(query, conn)

df

DatabaseError: Execution failed on sql '
select Name, Age, Survived from titanic df['Age'].mean()
': near "['Age']": syntax error

In [ ]:
query = '''
select Name, Age, from titanic
'''
df = pd.read_sql(query, conn)

df